# Generated by Django 3.2.3 on 2021-05-19 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='publicacao_comentario',
            new_name='publicado_comentario',
        ),
    ]
