name: Aplicação Django

on: [pull_request]

jobs:
  builds:
    env:
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTULENVS: 1
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Instalar Dependências
        run: |
          pip install pipenv
          pipenv sync --dev
